
#include "os/include/WordFilter.h"

using namespace IGame;

int main()
{
    WordFilter filter;
    std::vector<std::string> tmpVector;
    tmpVector.push_back("fuck");
    tmpVector.push_back("大东亚");
    tmpVector.push_back("戳比");
    tmpVector.push_back("戳逼");
    tmpVector.push_back("戳b");
    tmpVector.push_back("戳B");
    tmpVector.push_back("吹箫");
    tmpVector.push_back("传销");
    tmpVector.push_back("处女");
    tmpVector.push_back("陈水扁");
    tmpVector.push_back("常委");
    tmpVector.push_back("娼妓");
    tmpVector.push_back("娼妇");
    tmpVector.push_back("插你");
    tmpVector.push_back("操逼");
    tmpVector.push_back("藏独");
    tmpVector.push_back("藏毒");
    tmpVector.push_back("布什");
    tmpVector.push_back("瘪三");
    tmpVector.push_back("婊子");
    tmpVector.push_back("避孕套");
    tmpVector.push_back("本拉登");
    tmpVector.push_back("包皮");
    tmpVector.push_back("八九学潮");
    tmpVector.push_back("安南");
    tmpVector.push_back("爱兹");
    tmpVector.push_back("Gm");
    tmpVector.push_back("GM");
    tmpVector.push_back("东亚病夫");
    tmpVector.push_back("东突厥");
    tmpVector.push_back("东京");
    tmpVector.push_back("腚眼");
    tmpVector.push_back("钓鱼台");
    tmpVector.push_back("钓鱼岛");
    tmpVector.push_back("帝国");
    tmpVector.push_back("邓小平");
    tmpVector.push_back("荡妇");
    tmpVector.push_back("大血逼");
    tmpVector.push_back("大血b");
    tmpVector.push_back("大血B");
    tmpVector.push_back("大统");
    tmpVector.push_back("大世纪");
    tmpVector.push_back("大日本帝国");
    tmpVector.push_back("大纪元");
    tmpVector.push_back("大法弟子");
    tmpVector.push_back("大法");
    tmpVector.push_back("共产党");
    tmpVector.push_back("公投");
    tmpVector.push_back("管理员");
    tmpVector.push_back("高潮");
    tmpVector.push_back("戆比");
    tmpVector.push_back("戆逼");
    tmpVector.push_back("戆b");
    tmpVector.push_back("戆B");
    tmpVector.push_back("肛门");
    tmpVector.push_back("肛交");
    tmpVector.push_back("干你");
    tmpVector.push_back("干比");
    tmpVector.push_back("干逼");
    tmpVector.push_back("干b");
    tmpVector.push_back("干B");
    tmpVector.push_back("反人民");
    tmpVector.push_back("反共m");
    tmpVector.push_back("反革命");
    tmpVector.push_back("反动");
    tmpVector.push_back("反党");
    tmpVector.push_back("法轮功");
    tmpVector.push_back("法轮");
    tmpVector.push_back("独立");
    tmpVector.push_back("独裁");
    tmpVector.push_back("毒品");
    tmpVector.push_back("疆毒");
    tmpVector.push_back("江主席");
    tmpVector.push_back("江泽民");
    tmpVector.push_back("贱种");
    tmpVector.push_back("贱逼");
    tmpVector.push_back("贱b");
    tmpVector.push_back("贱B");
    tmpVector.push_back("贾庆林");
    tmpVector.push_back("妓女");
    tmpVector.push_back("鸡吧");
    tmpVector.push_back("机八");
    tmpVector.push_back("黄片");
    tmpVector.push_back("黄惠江");
    tmpVector.push_back("黄菊");
    tmpVector.push_back("皇军");
    tmpVector.push_back("胡主席");
    tmpVector.push_back("胡锦涛");
    tmpVector.push_back("黑社会");
    tmpVector.push_back("黑人");
    tmpVector.push_back("核武器");
    tmpVector.push_back("汉奸");
    tmpVector.push_back("国务院");
    tmpVector.push_back("国民党");
    tmpVector.push_back("鬼子");
    tmpVector.push_back("龟头");
    tmpVector.push_back("官方");
    tmpVector.push_back("狗日");
    tmpVector.push_back("狗屁");
    tmpVector.push_back("狗娘");
    tmpVector.push_back("共青团");
    tmpVector.push_back("共军");
    tmpVector.push_back("共和");
    tmpVector.push_back("共匪");
    tmpVector.push_back("共党");
    tmpVector.push_back("共产主义");
    tmpVector.push_back("卖逼");
    tmpVector.push_back("妈");
    tmpVector.push_back("罗干");
    tmpVector.push_back("卵子");
    tmpVector.push_back("六四");
    tmpVector.push_back("刘少奇");
    tmpVector.push_back("林肯");
    tmpVector.push_back("林巍");
    tmpVector.push_back("李瑞环");
    tmpVector.push_back("李鹏");
    tmpVector.push_back("李岚清");
    tmpVector.push_back("李洪志");
    tmpVector.push_back("李宏志");
    tmpVector.push_back("李长春");
    tmpVector.push_back("拉登");
    tmpVector.push_back("口交");
    tmpVector.push_back("口暴");
    tmpVector.push_back("恐怖分子");
    tmpVector.push_back("客服GM");
    tmpVector.push_back("客服");
    tmpVector.push_back("精子");
    tmpVector.push_back("精液");
    tmpVector.push_back("金廷勋");
    tmpVector.push_back("叫床");
    tmpVector.push_back("蒋介石");
    tmpVector.push_back("疆独");
    tmpVector.push_back("宋庆龄");
    tmpVector.push_back("鼠疫");
    tmpVector.push_back("山口组");
    tmpVector.push_back("三个代表");
    tmpVector.push_back("三K党");
    tmpVector.push_back("萨达姆");
    tmpVector.push_back("日军");
    tmpVector.push_back("日逼");
    tmpVector.push_back("日本");
    tmpVector.push_back("人民币");
    tmpVector.push_back("人大");
    tmpVector.push_back("强奸");
    tmpVector.push_back("屁眼");
    tmpVector.push_back("娘的");
    tmpVector.push_back("你娘");
    tmpVector.push_back("你母");
    tmpVector.push_back("你老母");
    tmpVector.push_back("纳粹");
    tmpVector.push_back("灭中");
    tmpVector.push_back("灭日");
    tmpVector.push_back("梅毒");
    tmpVector.push_back("毛主席");
    tmpVector.push_back("毛泽东");
    tmpVector.push_back("毛片");
    tmpVector.push_back("卖淫");
    tmpVector.push_back("卖比");
    tmpVector.push_back("杨燕姬");
    tmpVector.push_back("扬耀");
    tmpVector.push_back("畜生");
    tmpVector.push_back("性欲强");
    tmpVector.push_back("性无能");
    tmpVector.push_back("性交");
    tmpVector.push_back("新疆独立");
    tmpVector.push_back("邪教");
    tmpVector.push_back("小泉纯一郎");
    tmpVector.push_back("小鸡鸡");
    tmpVector.push_back("系统公告");
    tmpVector.push_back("西藏独立");
    tmpVector.push_back("吴仪");
    tmpVector.push_back("吴官正");
    tmpVector.push_back("吴邦国");
    tmpVector.push_back("龌龊");
    tmpVector.push_back("文革");
    tmpVector.push_back("温家宝");
    tmpVector.push_back("卫生巾");
    tmpVector.push_back("猥亵");
    tmpVector.push_back("王八蛋");
    tmpVector.push_back("王八");
    tmpVector.push_back("天安门事件");
    tmpVector.push_back("太子党");
    tmpVector.push_back("台湾独立");
    tmpVector.push_back("台湾");
    tmpVector.push_back("台独");
    tmpVector.push_back("台毒");
    tmpVector.push_back("做爱");
    tmpVector.push_back("祖宗");
    tmpVector.push_back("走狗");
    tmpVector.push_back("自焚");
    tmpVector.push_back("主席");
    tmpVector.push_back("朱镕基");
    tmpVector.push_back("朱德");
    tmpVector.push_back("周总理");
    tmpVector.push_back("周恩来");
    tmpVector.push_back("中南海");
    tmpVector.push_back("中华人民共和国");
    tmpVector.push_back("中华民国");
    tmpVector.push_back("中国");
    tmpVector.push_back("中共中央");
    tmpVector.push_back("中共");
    tmpVector.push_back("支那");
    tmpVector.push_back("政治");
    tmpVector.push_back("政府");
    tmpVector.push_back("珍宝岛");
    tmpVector.push_back("曾庆红");
    tmpVector.push_back("造反");
    tmpVector.push_back("杂种");
    tmpVector.push_back("杂碎");
    tmpVector.push_back("运营");
    tmpVector.push_back("月经");
    tmpVector.push_back("游戏管理员");
    tmpVector.push_back("隐瞒疫情");
    tmpVector.push_back("淫娃");
    tmpVector.push_back("阴唇");
    tmpVector.push_back("阴部");
    tmpVector.push_back("伊拉克");
    tmpVector.push_back("伊拉克");
    tmpVector.push_back("摇头丸");
    tmpVector.push_back("杨耀");
    tmpVector.push_back("操");
    tmpVector.push_back("游戏");

    
    std::vector<std::string> tmpVector1;
    filter.AddWords(tmpVector);

    char buf[1234] = "操暗操暗啊操啊打发地方";

    filter.AddWord("操");

    std::string xx = "aFu操Ckb曾庆红ads日本af操逼adkjf操你妈比游戏管理员打发法游戏啊#啊##啊";

    printf("src:%s\n", xx.c_str());

    int x = filter.Check(xx.c_str());

    filter.CheckAndModify(xx);

    printf("dst:%s\n", xx.c_str());
    return 0;
}



